### ISSUE TITLE
Wiki on the Project

### ISSUE THREAD

**Issue by vittoso** [antonyakushin/Intellibox#6]
Hi,
I took the liberty to experiment a bit with GitHub wiki and tried to recreate the original Intellibox documentation on the Codeplex page using the web.archive.org (as at the moment, you cannot really open the "Installation Instructions" and "Getting Started" links on Codeplex - they're not working).

I create the Wiki on [my fork](https://github.com/vittoso/Intellibox/wiki).

If you appreciate it I am perfectly willing to contribute and implement those pages on the main repo.

**Comment by antonyakushin** [comment]
Looks great! Happy to add you to the repo.

Please note that I'm not the original author, but after trying to contact the authors of Intellibox on CodePlex (and on GitHub too), I gave up and started to maintain it myself.

**Comment by vittoso** [comment]
Thank you @antonyakushin 
Wiki created and data commited.
It can be improved of course but...it's a start!
